window.content.enemies = [
    {
        name: 'Young Wolf',
        portrait: 'wolf',
        portraitId: 1,
        maxHp: 40,
        hp: 40,
        level: null,
        minLevel: 1,
        maxLevel: 2,
        type: 'normal', // 'normal', 'rare', 'rareElite', 'elite', 'boss'
        killCount: 0,
        minMoney: null, // need to update how minMoney and maxMoney work, level will work in range
        maxMoney: null,
        lootTable: [0],
    },
    {
        name: 'Kobold',
        portrait: 'kobold',
        portraitId: 1,
        maxHp: 110,
        hp: 110,
        level: null,
        minLevel: 1,
        maxLevel: 3,
        type: 'normal',
        killCount: 0,
        minMoney: null,
        maxMoney: null,
        lootTable: [0],
    },
    {
        name: 'Bandit',
        portrait: 'defias',
        portraitId: 1,
        maxHp: 190,
        hp: 190,
        level: null,
        minLevel: 2,
        maxLevel: 4,
        type: 'normal',
        killCount: 0,
        minMoney: null,
        maxMoney: null,
        lootTable: [0],
    },
    {
        name: 'Boar',
        portrait: 'boar',
        portraitId: 2,
        maxHp: 280,
        hp: 280,
        level: null,
        minLevel: 3,
        maxLevel: 5,
        type: 'normal',
        killCount: 0,
        minMoney: null,
        maxMoney: null,
        lootTable: [],
    },
    {
        name: 'Forest Spider',
        portrait: 'tarantula',
        portraitId: 3,
        maxHp: 200,
        hp: 200,
        level: null,
        minLevel: 3,
        maxLevel: 6,
        type: 'normal',
        killCount: 0,
        minMoney: null,
        maxMoney: null,
        lootTable: [],
    },
    {
        name: 'Murloc',
        portrait: 'murloc',
        portraitId: 1,
        maxHp: 200,
        hp: 200,
        level: null,
        minLevel: 4,
        maxLevel: 6,
        type: 'normal',
        killCount: 0,
        minMoney: null,
        maxMoney: null,
        lootTable: [],
    },
    {
        name: 'Bear',
        portrait: 'bear',
        portraitId: 1,
        maxHp: 200,
        hp: 200,
        level: null,
        minLevel: 7,
        maxLevel: 8,
        type: 'normal',
        killCount: 0,
        minMoney: null,
        maxMoney: null,
        lootTable: [],
    },
    {
        name: 'Rivepaw Gnoll',
        portrait: 'gnoll',
        portraitId: 1,
        maxHp: 200,
        hp: 200,
        level: null,
        minLevel: 6,
        maxLevel: 9,
        type: 'normal',
        killCount: 0,
        minMoney: null,
        maxMoney: null,
        lootTable: [],
    },
]