window.content.merchants = [
    {
        id: 0,
        requiredLevel: 0, // If i add achievements later, some merchant may have achievement requirements
        name: 'Smith Marcus',
        type: 'Black-smith',
        stock: [1,2,4],
    },
    {
        id: 1,
        requiredLevel: 5,
        name: '',
        type: '',
        stock: [],
    },
    {
        id: 2,
        requiredLevel: 5,
        name: '',
        type: '',
        stock: [],
    },
    {
        id: 3,
        requiredLevel: 5,
        name: '',
        type: '',
        stock: [],
    },
    {
        id: 4,
        requiredLevel: 5,
        name: '',
        type: '',
        stock: [],
    },
    {
        id: 5,
        requiredLevel: 5,
        name: '',
        type: '',
        stock: [],
    },
    {
        id: 6,
        requiredLevel: 5,
        name: '',
        type: '',
        stock: [],
    },
    {
        id: 7,
        requiredLevel: 5,
        name: '',
        type: '',
        stock: [],
    },
    {
        id: 8,
        requiredLevel: 5,
        name: '',
        type: '',
        stock: [],
    },
    {
        id: 9,
        requiredLevel: 5,
        name: '',
        type: '',
        stock: [],
    },
]